[package]
name = "opengl_rust"
version = "0.1.0"
authors = ["Tom Anderson <tom@ando.gq>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
